server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      mvc:
        cors:
          configurations:
            '[/**]':
              allowedOrigins:
                - "http://localhost:5173"
                - "http://localhost:5174"
                - "http://localhost:3000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
                - PATCH
              allowedHeaders: "*"
              allowCredentials: true
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
            - id: attendance-service
              uri: lb://attendance-service
              predicates:
                - Path=/api/attendance/**
            - id: leave-service
              uri: lb://leave-service
              predicates:
                - Path=/api/leaves/**
            - id: hr-service
              uri: lb://hr-service
              predicates:
                - Path=/api/hr/**

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics,gateway"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
