server.port=8083
spring.application.name=leave-service

# Dedicated database for leave-service
spring.datasource.url=jdbc:mysql://localhost:3306/leave_mgmt_leave?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
