server.port=8085
spring.application.name=notification-service
# Exclude DataSourceAutoConfiguration just in case, though it shouldn't activate without JPA
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
